### ISSUE TITLE
Please provide complete list of MIME types

### ISSUE THREAD

**Issue by MyWek** [OutcomeBet/casino25-games-static#1]
It seems every time a new game is released new and strange mime types needed to be added to web.config, and it's only when a game fails to load that we discover this.  It would be great to have a complete list of web server extensions, rewrites etc that need to be added.

**Comment by Scukerman** [comment]
We update the config every time when changes are needed. Therefore, this config is up-to-date.
What kind of issues do you experience?
If you have some screenshots or troubles, please provide with related information to debug this to your manager.

Thanks for you patience and interest to this repository.
